spring:
  application:
    name: reservation-service
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: reservation-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
      endpoint: ${OTEL_ENDPOINT:http://otel-collector:4318/v1/traces}
logging:
  structured:
    format:
      console: logstash
server:
  shutdown: graceful
