{
 "title": "LogiCore WMS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Healthy services",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "up",
     "legendFormat": "{{job}} {{operation}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Go business operations / second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (service, operation, outcome) (rate(wms_operations_total[5m]))",
     "legendFormat": "{{job}} {{operation}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Java HTTP latency p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "{{job}} {{operation}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Java events processed",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(kafka_messages_processed_total[5m]))",
     "legendFormat": "{{job}} {{operation}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Process resident memory",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes",
     "legendFormat": "{{job}} {{operation}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Go goroutines",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "go_goroutines",
     "legendFormat": "{{job}} {{operation}} {{outcome}}"
    }
   ]
  }
 ]
}